bot:
  auth:
    token: ""
    owner-id: "403569609518743552"

messages:
  - "/messages/example.yml"


paste-settings:
  enabled: true
  cooldown:
    excluded-roles: []
    duration-in-sec: 10
  global: true
  channels: []